// ============= Lexer for SysY =============
tokens = { SOI ~ (TOKEN)* ~ EOI }

NEWLINE           = _{ "\r\n" | "\n" }
LINE_COMMENT      = _{ "//" ~ (!NEWLINE ~ ANY)* ~ NEWLINE }
MULTILINE_COMMENT = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
WHITESPACE        = _{ " " | "\t" | NEWLINE | LINE_COMMENT | MULTILINE_COMMENT }

Const    = @{ "const" ~ !ASCII_ALPHANUMERIC ~ !"_" }
Int      = @{ "int" ~ !ASCII_ALPHANUMERIC ~ !"_" }
Void     = @{ "void" ~ !ASCII_ALPHANUMERIC ~ !"_" }
If       = @{ "if" ~ !ASCII_ALPHANUMERIC ~ !"_" }
Else     = @{ "else" ~ !ASCII_ALPHANUMERIC ~ !"_" }
While    = @{ "while" ~ !ASCII_ALPHANUMERIC ~ !"_" }
Break    = @{ "break" ~ !ASCII_ALPHANUMERIC ~ !"_" }
Continue = @{ "continue" ~ !ASCII_ALPHANUMERIC ~ !"_" }
Return   = @{ "return" ~ !ASCII_ALPHANUMERIC ~ !"_" }

Ident = @{ !KEYWORD ~ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

Eq        = { "==" }
Neq       = { "!=" }
Le        = { "<=" }
Ge        = { ">=" }
And       = { "&&" }
Or        = { "||" }
Plus      = { "+" }
Minus     = { "-" }
Mul       = { "*" }
Div       = { "/" }
Mod       = { "%" }
Assign    = { "=" }
Lt        = { "<" }
Gt        = { ">" }
Not       = { "!" }
LParen    = { "(" }
RParen    = { ")" }
LBrace    = { "{" }
RBrace    = { "}" }
LBracket  = { "[" }
RBracket  = { "]" }
Comma     = { "," }
Semicolon = { ";" }

IntegerConst = @{
    "0x" ~ ASCII_HEX_DIGIT+
  | "0X" ~ ASCII_HEX_DIGIT+
  | "0" ~ ASCII_OCT_DIGIT*
  | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*
}

COMMENT  = _{ LINE_COMMENT | MULTILINE_COMMENT }
KEYWORD  = _{ Const | Int | Void | If | Else | While | Break | Continue | Return }
OPERATOR = _{ Eq | Neq | Le | Ge | And | Or | Assign | Mul | Div | Plus | Minus | Mod | Lt | Gt | Not }
TOKEN    = _{
    COMMENT
  | KEYWORD
  | Ident
  | OPERATOR
  | LParen
  | RParen
  | LBrace
  | RBrace
  | LBracket
  | RBracket
  | Comma
  | Semicolon
  | IntegerConst
}

// ============= Parser for SysY =============
prog = { SOI ~ CompUnit ~ EOI }

CompUnit = { (FuncDef | Decl | TopError)+ }

Decl = { ConstDecl | VarDecl }
DeclError = @{ (!Semicolon ~ ANY)* ~ Semicolon }

BType = @{ Int }

ConstDecl    = { Const ~ ((BType ~ ConstDef ~ (Comma ~ ConstDef)* ~ Semicolon) | DeclError) }
ConstDef     = { Ident ~ (LBracket ~ ConstExp ~ RBracket)* ~ Assign ~ ConstInitVal }
ConstInitVal = { ConstExp | LBrace ~ (ConstInitVal ~ (Comma ~ ConstInitVal)*)? ~ RBrace }

VarDecl = { BType ~ ((VarDef ~ (Comma ~ VarDef)* ~ Semicolon) | DeclError) }
VarDef  = { Ident ~ (LBracket ~ ConstExp ~ RBracket)* ~ (Assign ~ InitVal)? }
InitVal = { Exp | LBrace ~ (InitVal ~ (Comma ~ InitVal)*)? ~ RBrace }

FuncDef     = { FuncType ~ Ident ~ LParen ~ (FuncFParams)? ~ RParen ~ Block }
FuncType    = { Void | BType }
FuncFParams = { FuncFParam ~ (Comma ~ FuncFParam)* }
FuncFParam  = { BType ~ Ident ~ (LBracket ~ RBracket ~ (LBracket ~ Exp ~ RBracket)*)? }

Block     = { LBrace ~ (BlockItem)* ~ RBrace }
BlockItem = { Decl | Stmt }

Stmt = {
    LVal ~ Assign ~ Exp ~ Semicolon
  | (Exp)? ~ Semicolon
  | Block
  | If ~ LParen ~ Cond ~ RParen ~ Stmt ~ (Else ~ Stmt)?
  | While ~ LParen ~ Cond ~ RParen ~ Stmt
  | Break ~ Semicolon
  | Continue ~ Semicolon
  | Return ~ (Exp)? ~ Semicolon
  | StmtError
}
StmtError = @{ (!(Semicolon | RBrace) ~ ANY)+ ~ (Semicolon)?}

Exp         = { Cond | AddExp }
Cond        = { OrExp }
LVal        = { Ident ~ (LBracket ~ Exp ~ RBracket)* }
PrimaryExp  = { LParen ~ Exp ~ RParen | LVal | Number }
Number      = { IntegerConst }
UnaryExp    = { Ident ~ LParen ~ (FuncRParams)? ~ RParen | PrimaryExp | UnaryOp ~ UnaryExp }
UnaryOp     = { Plus | Minus | Not }
FuncRParams = { Exp ~ (Comma ~ Exp)* }
MulExp      = { UnaryExp ~ ((Mul | Div | Mod) ~ UnaryExp)* }
AddExp      = { MulExp ~ ((Plus | Minus) ~ MulExp)* }
RelExp      = { AddExp ~ ((Le | Ge | Lt | Gt) ~ AddExp)* }
EqExp       = { RelExp ~ ((Eq | Neq) ~ RelExp)* }
AndExp      = { EqExp ~ (And ~ EqExp)* }
OrExp       = { AndExp ~ (Or ~ AndExp)* }
ConstExp    = { AddExp }

TopError = @{ (ANY)+ ~ EOI }