NEWLINE = _{ "\r\n" | "\n" }
LINE_COMMENT = _{ "//" ~ (!NEWLINE ~ ANY)* ~ NEWLINE }
MULTILINE_COMMENT = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
WHITESPACE = _{ " " | "\t" | NEWLINE | LINE_COMMENT | MULTILINE_COMMENT }

CONST    = @{ "const" ~ !ASCII_ALPHANUMERIC ~ !"_" }
INT      = @{ "int" ~ !ASCII_ALPHANUMERIC ~ !"_" }
VOID     = @{ "void" ~ !ASCII_ALPHANUMERIC ~ !"_" }
IF       = @{ "if" ~ !ASCII_ALPHANUMERIC ~ !"_" }
ELSE     = @{ "else" ~ !ASCII_ALPHANUMERIC ~ !"_" }
WHILE    = @{ "while" ~ !ASCII_ALPHANUMERIC ~ !"_" }
BREAK    = @{ "break" ~ !ASCII_ALPHANUMERIC ~ !"_" }
CONTINUE = @{ "continue" ~ !ASCII_ALPHANUMERIC ~ !"_" }
RETURN   = @{ "return" ~ !ASCII_ALPHANUMERIC ~ !"_" }

IDENT = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

PLUS      = { "+" }
MINUS     = { "-" }
MUL       = { "*" }
DIV       = { "/" }
MOD       = { "%" }
ASSIGN    = { "=" }
EQ        = { "==" }
NEQ       = { "!=" }
LT        = { "<" }
GT        = { ">" }
LE        = { "<=" }
GE        = { ">=" }
NOT       = { "!" }
AND       = { "&&" }
OR        = { "||" }
L_PAREN   = { "(" }
R_PAREN   = { ")" }
L_BRACE   = { "{" }
R_BRACE   = { "}" }
L_BRACKT  = { "[" }
R_BRACKT  = { "]" }
COMMA     = { "," }
SEMICOLON = { ";" }

INTEGER_CONST = @{
    "0x" ~ ASCII_HEX_DIGIT+
  | "0X" ~ ASCII_HEX_DIGIT+
  | "0" ~ ASCII_OCT_DIGIT*
  | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*
}

comment  = _{ LINE_COMMENT | MULTILINE_COMMENT }
keyword  = _{ CONST | INT | VOID | IF | ELSE | WHILE | BREAK | CONTINUE | RETURN }
operator = _{ EQ | NEQ | LE | GE | AND | OR | ASSIGN | MUL | DIV | PLUS | MINUS | MOD | LT | GT | NOT }
token    = _{
    comment
  | keyword
  | IDENT
  | operator
  | L_PAREN
  | R_PAREN
  | L_BRACE
  | R_BRACE
  | L_BRACKT
  | R_BRACKT
  | COMMA
  | SEMICOLON
  | INTEGER_CONST
}

tokenize = { SOI ~ (token)* ~ EOI }
